/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbc.program;
import javax.swing.DefaultListModel;
import java.util.*;
import jdbc.model.Mahasiswa;
import jdbc.service.MysqlMahasiswaService;

/**
 *
 * @author ASUS
 */
public class JFrameUtama extends javax.swing.JFrame {
    DefaultListModel<String> dlm;
    DefaultListModel<String> nim;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameUtama.class.getName());
    static MysqlMahasiswaService service = new MysqlMahasiswaService();
    /**
     * Creates new form JFrameUtama
     */
    public JFrameUtama() {
        initComponents();
        this.dlm = new DefaultListModel<>();
        this.nim = new DefaultListModel<>();
        JListNama.setModel(dlm);
        JListID.setModel(nim);
        dlm.clear();
        nim.clear();
        loadMahasiswa();
    }
    
    private void addNama(Mahasiswa halo){
        dlm.addElement(halo.getNama());
        
    }
    private void addNim(Mahasiswa halo){
        nim.addElement(String.valueOf(halo.getId()));
        
    }
    public void loadMahasiswa() {

        List<Mahasiswa> data = service.getAll();

        DefaultListModel<String> modelNama =
            new DefaultListModel<>();

        DefaultListModel<String> modelNim =
            new DefaultListModel<>();

        for (Mahasiswa m : data) {
            modelNama.addElement(m.getNama());
            modelNim.addElement(String.valueOf(m.getId()));
        }
        JListNama.setModel(modelNama);
        JListID.setModel(modelNim);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        JListID = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        JListNama = new javax.swing.JList<>();
        JLabelID = new javax.swing.JLabel();
        JLabelNama = new javax.swing.JLabel();
        JLabelJudul = new javax.swing.JLabel();
        JButtonNama = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JTextFieldNama = new javax.swing.JTextField();
        JButtonTambah = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        JButtonEdit = new javax.swing.JButton();
        JButtonHapus = new javax.swing.JButton();
        JButtonIndeks = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JListID.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(JListID);

        JListNama.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(JListNama);

        JLabelID.setText("ID");

        JLabelNama.setText("Nama");

        JLabelJudul.setText("Kelola Data Mahasiswa");

        JButtonNama.setText("Ambil Semua Data");
        JButtonNama.addActionListener(this::JButtonNamaActionPerformed);

        jLabel1.setText("nama:");

        JTextFieldNama.addActionListener(this::JTextFieldNamaActionPerformed);

        JButtonTambah.setText("Tambahkan");
        JButtonTambah.addActionListener(this::JButtonTambahActionPerformed);

        jTextField3.addActionListener(this::jTextField3ActionPerformed);

        JButtonEdit.setText("Edit");
        JButtonEdit.addActionListener(this::JButtonEditActionPerformed);

        JButtonHapus.setText("Hapus");
        JButtonHapus.addActionListener(this::JButtonHapusActionPerformed);

        JButtonIndeks.setText("Reset Indeks");
        JButtonIndeks.addActionListener(this::JButtonIndeksActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLabelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JButtonIndeks)
                    .addComponent(JButtonNama)
                    .addComponent(JLabelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JButtonEdit))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JButtonHapus))))
                    .addComponent(JTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JButtonTambah))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelID)
                    .addComponent(JLabelNama)
                    .addComponent(JLabelJudul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JButtonNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JButtonTambah)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JButtonEdit))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JButtonHapus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(JButtonIndeks))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButtonNamaActionPerformed

    private void JTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldNamaActionPerformed

    private void JButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonTambahActionPerformed
        Mahasiswa mhsAdd = new Mahasiswa(JTextFieldNama.getText());
        service.add(mhsAdd);
        JTextFieldNama.setText("");
        addNama(mhsAdd);
        addNim(service.getByName(mhsAdd.getNama()));
        loadMahasiswa();
    }//GEN-LAST:event_JButtonTambahActionPerformed

    private void JButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonEditActionPerformed
        Mahasiswa mhsUpdate = service.getById(Integer.parseInt(jTextField1.getText()));
        if (mhsUpdate != null) {
            mhsUpdate.setNama(jTextField3.getText());
            service.update(mhsUpdate);
        }
        loadMahasiswa();
    }//GEN-LAST:event_JButtonEditActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void JButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonHapusActionPerformed

        int index = JListID.getSelectedIndex();
        jTextField4.setText("");
        int id = Integer.parseInt(JListID.getModel().getElementAt(index));
        service.delete(id);
        loadMahasiswa();
    }//GEN-LAST:event_JButtonHapusActionPerformed

    private void JButtonIndeksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonIndeksActionPerformed
       service.resetIndex();
    }//GEN-LAST:event_JButtonIndeksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonEdit;
    private javax.swing.JButton JButtonHapus;
    private javax.swing.JButton JButtonIndeks;
    private javax.swing.JButton JButtonNama;
    private javax.swing.JButton JButtonTambah;
    private javax.swing.JLabel JLabelID;
    private javax.swing.JLabel JLabelJudul;
    private javax.swing.JLabel JLabelNama;
    private javax.swing.JList<String> JListID;
    private javax.swing.JList<String> JListNama;
    private javax.swing.JTextField JTextFieldNama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
